#!/bin/bash
# Fresh Render Deployment Setup Script

echo "=============================================="
echo "   FRESH RENDER SERVICE SETUP GUIDE"
echo "=============================================="
echo ""
echo "STEP 1: Delete Old Service"
echo "----------------------------"
echo "1. Go to: https://dashboard.render.com"
echo "2. Find service: volatisense-api (srv-d49hca8dl3ps739kd35g)"
echo "3. Click on it → Settings → Scroll to bottom"
echo "4. Click 'Delete Service' → Confirm"
echo ""
echo "Press Enter when you've deleted the old service..."
read -r

echo ""
echo "STEP 2: Create NEW Web Service"
echo "--------------------------------"
echo "1. On Render Dashboard, click 'New +' → 'Web Service'"
echo "2. Click 'Build and deploy from a Git repository'"
echo "3. Connect to your GitHub repository: adarshalexbalmuchu/FX"
echo "4. Click 'Connect'"
echo ""
echo "Press Enter when you've connected the repository..."
read -r

echo ""
echo "STEP 3: Configure the Service"
echo "-------------------------------"
echo "Copy these EXACT settings:"
echo ""
echo "Name: volatisense-backend"
echo "Region: Oregon (US West)"
echo "Branch: main"
echo "Runtime: Python 3"
echo ""
echo "⚠️  CRITICAL ⚠️"
echo "Root Directory: [LEAVE THIS COMPLETELY EMPTY!]"
echo ""
echo "Build Command:"
echo "pip install --upgrade pip setuptools wheel && pip install -r backend/requirements.txt"
echo ""
echo "Start Command:"
echo "cd backend && uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "Instance Type: Free"
echo ""
echo "Press Enter when you've entered these settings..."
read -r

echo ""
echo "STEP 4: Add Environment Variables"
echo "-----------------------------------"
echo "Click 'Advanced' → Add these environment variables:"
echo ""
echo "PYTHON_VERSION = 3.11.9"
echo "ENVIRONMENT = production"
echo "CORS_ORIGINS = https://adarshalexbalmuchu.github.io"
echo "PYTHONUNBUFFERED = 1"
echo ""
echo "Press Enter when you've added all environment variables..."
read -r

echo ""
echo "STEP 5: Create Service"
echo "-----------------------"
echo "Click 'Create Web Service' button"
echo ""
echo "Render will now:"
echo "  - Clone your repository"
echo "  - Read runtime.txt → Install Python 3.11.9"
echo "  - Install dependencies from backend/requirements.txt"
echo "  - Start uvicorn server"
echo ""
echo "This will take 3-5 minutes for first deploy."
echo ""
echo "Press Enter to see what to watch for in build logs..."
read -r

echo ""
echo "STEP 6: Monitor Build Logs"
echo "---------------------------"
echo "Watch for these SUCCESS indicators:"
echo "  ✅ 'Installing Python version 3.11.9'"
echo "  ✅ 'pip install -r backend/requirements.txt'"
echo "  ✅ 'Successfully installed pandas-2.1.4'"
echo "  ✅ 'Successfully installed fastapi-0.104.1'"
echo "  ✅ 'Your service is live 🎉'"
echo ""
echo "❌ If you see 'Python 3.13' - STOP and restart this process!"
echo ""
echo "Press Enter when service shows 'Live' status..."
read -r

echo ""
echo "STEP 7: Test Your Deployment"
echo "------------------------------"
echo "You'll get a new URL like: https://volatisense-backend-xxxx.onrender.com"
echo ""
echo "Test these endpoints:"
echo ""
echo "1. Health check:"
echo "   https://YOUR-NEW-URL.onrender.com/"
echo ""
echo "2. API Documentation:"
echo "   https://YOUR-NEW-URL.onrender.com/docs"
echo ""
echo "3. Test simulation:"
echo "   curl -X POST https://YOUR-NEW-URL.onrender.com/api/simulate \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"export_share\": 0.4, \"import_share\": 0.3, \"fx_volatility\": 0.15, \"hedge_ratio\": 0.5}'"
echo ""
echo "Press Enter when all tests pass..."
read -r

echo ""
echo "STEP 8: Update Frontend Configuration"
echo "---------------------------------------"
echo "Your new backend URL needs to be added to GitHub Actions"
echo ""
echo "I'll update the workflow file now..."
echo ""

# Get the new URL from user
echo "Enter your NEW Render URL (e.g., https://volatisense-backend-abc123.onrender.com):"
read -r NEW_URL

if [ -n "$NEW_URL" ]; then
    echo ""
    echo "Updating GitHub Actions workflow with new URL: $NEW_URL"
    
    # Update the GitHub Actions workflow
    sed -i "s|VITE_API_URL:.*|VITE_API_URL: $NEW_URL|g" .github/workflows/github-pages.yml
    
    echo "Updated! Now committing and pushing..."
    git add .github/workflows/github-pages.yml
    git commit -m "Update API URL to new Render deployment"
    git push origin main
    
    echo ""
    echo "✅ GitHub Actions workflow updated!"
    echo ""
fi

echo ""
echo "STEP 9: Enable GitHub Pages"
echo "----------------------------"
echo "1. Go to: https://github.com/adarshalexbalmuchu/FX/settings/pages"
echo "2. Source: GitHub Actions"
echo "3. Wait for deployment (check Actions tab)"
echo "4. Your frontend will be live at:"
echo "   https://adarshalexbalmuchu.github.io/FX/"
echo ""
echo "Press Enter when GitHub Pages is deployed..."
read -r

echo ""
echo "=============================================="
echo "          🎉 DEPLOYMENT COMPLETE! 🎉"
echo "=============================================="
echo ""
echo "Your VolatiSense app is now live:"
echo ""
echo "Backend API: $NEW_URL"
echo "Frontend UI: https://adarshalexbalmuchu.github.io/FX/"
echo ""
echo "Next steps:"
echo "  - Test all features in the frontend"
echo "  - Monitor Render logs for any errors"
echo "  - Remember: Free tier sleeps after 15min inactivity"
echo ""
echo "Happy deploying! 🚀"
echo "=============================================="
